### ISSUE TITLE
Request to support `slack api_url_file` and `pagerduty routing_key_file` options

### ISSUE THREAD

**Issue by jnavarrof** [fgouteroux/terraform-provider-mimir#45]
Alertmanger supports both configuration options in [Slack](https://prometheus.io/docs/alerting/latest/configuration/#slack_config) and [Pagerduty](https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config) to use a file containing the secret rather than injecting credentials in Terraform. This will simplify the setup and management of credentials for complex Alertmanager configurations defining multiple channels and pagerduty teams.  

Options mentioned above:

```
# The Slack webhook URL. Either api_url or api_url_file should be set.
[ api_url_file: [<filepath>](https://prometheus.io/docs/alerting/latest/configuration/#filepath) | default = global.slack_api_url_file ]
```

```
# The PagerDuty integration key (when using PagerDuty integration type `Events API v2`).
# Read the Pager Duty routing key from a file.
routing_key_file: [<filepath>](https://prometheus.io/docs/alerting/latest/configuration/#filepath)
```

It would be nice to support this.

**Comment by fgouteroux** [comment]
Hi @jnavarrof,

This is not possible because mimir doesn't support it. Many config file parameters are not supported, this is mainly caused by the multi tenants which is difficult to load a specific config file for a given tenant. Every alertmanager config is stored is s3 object storage.

You can check which parameters that are not supported by mimir:
https://github.com/grafana/mimir/blob/main/pkg/alertmanager/api.go

**Comment by jnavarrof** [comment]
Gi @fgouteroux ,

I see. I guess we will need to find another way. 

Many thanks!
